jobs:
  include:
    # - stage: create image
    #   os: linux
    #   dist: focal
    #   language: generic
    #   vm:
    #     create: 
    #       name: 2905-image

    - stage: use custom image
      vm:
        use: 2805-image2
      script:
        - echo "Running job with custom image"
