jobs:
  include:
    - stage: create image
      os: linux
      dist: focal
      language: generic
      vm:
        create: 
          name: 2905-image2

    - stage: use custom image
      vm:
        use: 2905-image2
      script:
        - echo "Running job with custom image"
